name: cooking
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.1.1
  provider: ^6.0.2
  http: ^0.13.3
  carousel_slider: ^4.0.0
  image_picker: ^0.8.2
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  camera: ^0.9.2+2
  path_provider: ^2.0.4
  path: ^1.8.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.9
  email_validator: ^2.0.1
  # To preload videos
  preload_page_view:
  # Video player
  cached_video_player:
  # Rating bar
  flutter_rating_bar:
  # Visibility of the widget listener
  visibility_detector:
  # Pausable timer
  pausable_timer:
  # To keep screen awake
  wakelock:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
